/**
 * Reads component source out of the `reacticx-codebase` R2 bucket.
 *
 * The bucket mirrors the library repo verbatim — `core/` is `src/components`,
 * `examples/` is `app/components`, `helpers/` is the shared utilities, and
 * `types/` is generated per component from its own type file — so the
 * docs show exactly what is in the repo rather than a snapshot that has to be
 * re-synced. `index.json` at the root lists every object, which is how a flat
 * component name resolves to a nested path.
 *
 * Everything here runs at build time, and the bucket is the only copy. The flat
 * per-kind directories that used to sit under the site root (`react-native/`,
 * `react-native-usage/`, `react-native-types/`) were a second copy of the same
 * files that had to be re-synced by hand, and are gone. A page whose object is
 * missing renders its own "not synced yet" note rather than failing the build.
 */

export const CODEBASE_ORIGIN = "https://pub-028ac77ff44d4123aed5b9b6592ec08d.r2.dev";

/** Bucket folder ← repo directory. Mirrors `cloudflare/codebase/config.ts`. */
export const CODEBASE_FOLDERS = {
  core: "core",
  examples: "examples",
  helpers: "helpers",
  /**
   * One `index.ts` per component, generated by `cloudflare/codebase/build-types.ts`
   * from whatever the component names its own type file. Resolving a slug to
   * its props is therefore the same shape as resolving one to its usage.
   */
  types: "types",
} as const;

interface IndexEntry {
  /** Path relative to the folder prefix, e.g. `base/button/index.tsx`. */
  path: string;
  /** Full object key, e.g. `core/base/button/index.tsx`. */
  key: string;
  size: number;
  hash: string;
  contentType: string;
}

interface CodebaseIndex {
  bucket: string;
  generatedAt: string;
  total: number;
  folders: Record<string, { prefix: string; source: string; files: IndexEntry[] }>;
}

const url = (key: string) =>
  `${CODEBASE_ORIGIN}/${key.split("/").map(encodeURIComponent).join("/")}`;

/**
 * How many requests one worker may have in flight at once.
 *
 * The 429s below are the bucket telling us we asked for too much at once, and
 * retrying harder is the wrong half of the answer on its own: nine prerender
 * workers each opening as many sockets as Node will give them is what provokes
 * the limit in the first place. Holding each worker to a handful keeps the
 * build inside what r2.dev will serve, so the retry only has to cover the
 * genuine blips rather than a self-inflicted stampede.
 */
const MAX_IN_FLIGHT = 6;

let inFlight = 0;
const waiting: Array<() => void> = [];

async function acquire() {
  if (inFlight < MAX_IN_FLIGHT) {
    inFlight += 1;
    return;
  }
  await new Promise<void>((resolve) => waiting.push(resolve));
  inFlight += 1;
}

function release() {
  inFlight -= 1;
  waiting.shift()?.();
}

/** `Retry-After`, in ms — the bucket's own answer beats our backoff curve. */
function retryAfter(response: Response) {
  const header = response.headers.get("retry-after");
  if (!header) return null;

  const seconds = Number(header);
  if (Number.isFinite(seconds)) return Math.max(0, seconds * 1000);

  const date = Date.parse(header);
  return Number.isNaN(date) ? null : Math.max(0, date - Date.now());
}

const sleep = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Fetches one object, retrying the failures that are worth retrying.
 *
 * A build prerenders hundreds of pages across nine workers, all reading from
 * the same bucket, so r2.dev rate-limits it (HTTP 429). Without a retry those
 * pages render their "not synced yet" note instead of the source — and because
 * the App Router derives a page's prefetch segment tree from what it rendered,
 * two pages that disagree about the same file leave the `.segments` output on
 * disk inconsistent and the build dies later in `next build` or in the OpenNext
 * bundler. Retrying keeps a build's view of the bucket the same throughout.
 *
 * Five attempts over about four seconds turned out to be short of what a full
 * catalogue build needs — a 429 that outlived them was reported as a missing
 * object, which is how a handful of pages shipped denying source that is in the
 * bucket. The budget is wider now, and a `Retry-After` is honoured over the
 * curve, because a build that waits a minute is strictly better than one that
 * publishes a component with no props.
 */
async function fetchWithRetry(key: string, attempts = 8): Promise<Response> {
  let lastError: Error | undefined;

  for (let attempt = 0; attempt < attempts; attempt++) {
    let response: Response;

    await acquire();
    try {
      response = await fetch(url(key), { cache: "no-store" });
    } catch (error) {
      // Connection reset, DNS blip, socket timeout — all worth another go.
      lastError = error as Error;
      // Exponential backoff, jittered so the workers don't retry in lockstep.
      const backoff = 250 * 2 ** attempt;
      await sleep(backoff + Math.random() * backoff);
      continue;
    } finally {
      release();
    }

    // 429 and 5xx are transient. Everything else — including 404, which means
    // the object genuinely is not in the bucket — is the answer.
    if (response.status !== 429 && response.status < 500) return response;

    lastError = new Error(`HTTP ${response.status}`);

    if (attempt === attempts - 1) break;

    const backoff = 250 * 2 ** attempt;
    await sleep(retryAfter(response) ?? backoff + Math.random() * backoff);
  }

  throw lastError ?? new Error("request failed");
}

/* -------------------------------------------------------------------------- */
/* index.json                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * One fetch per build, shared by every page.
 *
 * A rejected promise is not memoised — a transient failure on the first page
 * would otherwise poison every later one.
 */
let indexPromise: Promise<CodebaseIndex | null> | null = null;

/**
 * A build that cannot read the index has nothing to say about any component,
 * and it must not say it quietly.
 *
 * This used to warn and return null, on the strength of a fallback to synced
 * copies under the site root — copies that were deleted when the bucket became
 * the only source, leaving the null to mean "every component on this page is
 * missing". `next build` prerenders across several workers with an index cache
 * each, so one worker losing its fetch to an r2.dev 429 does not fail anything
 * or even look unusual: it just ships that worker's slice of the catalogue with
 * an empty file tree and "No props found" on every table, while the rest of the
 * build is perfect. That is exactly how nebula-orb and the four pages either
 * side of it went out claiming to be unsynced source that has been in the
 * bucket since August.
 *
 * So during a build the failure is fatal — the retry above has already given
 * the transient case five chances, and past that a wrong catalogue is worse
 * than no deploy. `next dev` keeps the old soft failure, since a laptop off the
 * network should still be able to render the prose half of a page.
 */
function onIndexFailure(error: Error): null {
  const message = `[codebase] could not load index.json: ${error.message}`;

  if (process.env.NODE_ENV === "production") {
    throw new Error(
      `${message}. Every component page reads its source and props from this ` +
        "listing, so building without it would publish the whole catalogue as " +
        '"not synced yet".',
    );
  }

  console.warn(`${message} — source and props will be missing from this page`);
  return null;
}

async function loadIndex(): Promise<CodebaseIndex | null> {
  indexPromise ??= (async () => {
    try {
      // Never cached across builds. This listing is the manifest of what the
      // bucket holds, so a persisted copy silently hides every component added
      // since — the page renders "not synced yet" for source that is right
      // there. One request per build, deduped in process by `indexPromise`.
      const response = await fetchWithRetry("index.json");
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return (await response.json()) as CodebaseIndex;
    } catch (error) {
      indexPromise = null;
      return onIndexFailure(error as Error);
    }
  })();

  return indexPromise;
}

/* -------------------------------------------------------------------------- */
/* name → key                                                                  */
/* -------------------------------------------------------------------------- */

/** `search-bar` -> `SearchBar`, matching how the repo names its main files. */
function toPascalCase(name: string) {
  return name
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

/**
 * The file names a component's entry point goes by, most canonical first.
 *
 * The repo is not uniform here — most folders use `index.tsx`, some re-export
 * from `index.ts`, and a few name the file after the component
 * (`SearchBar.tsx`, `FloatingSheet.tsx`). The flat sync resolved the same list,
 * so this keeps the docs showing the same file it used to.
 */
function mainCandidates(component: string) {
  const pascal = toPascalCase(component);
  return ["index.tsx", "index.ts", `${pascal}.tsx`, `${component}.tsx`];
}

/** Likewise for the types file that sits next to it. */
function typesCandidates(component: string) {
  const pascal = toPascalCase(component);
  return [
    "types.ts",
    `${pascal}.types.ts`,
    `${pascal}.props.ts`,
    "types/index.ts",
    "types.tsx",
  ];
}

/** The candidate list for a file the docs asks for by its canonical name. */
function candidatesFor(fileName: string, component: string) {
  if (fileName === "index.tsx") return mainCandidates(component);
  if (fileName === "types.ts") return typesCandidates(component);
  return [fileName];
}

/**
 * `Toast` and `toast` are the same component; so are `FloatingSheet` and
 * `floating-sheet`.
 *
 * The repo names most component directories in kebab case but not all of them,
 * and the docs slug is always kebab. Matching on a normalised name is what lets
 * `/components/toast` find `molecules/Toast/` instead of falling back to a flat
 * two-file listing that hides most of what the component ships.
 */
function normalizeDirName(name: string) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/[_\s]+/g, "-")
    .toLowerCase();
}

/** Files the source tree shows. Binaries in a component folder are skipped. */
const CODE_FILE = /\.(tsx?|jsx?|mjs|cjs|json|css|md|mdx)$/i;

interface ComponentFiles {
  /** Path of the component's own directory, relative to the folder prefix. */
  dir: string;
  /** Every file under it, keyed by path relative to `dir`. */
  files: Map<string, IndexEntry>;
}

type Lookup = Map<string, Map<string, ComponentFiles>>;

let lookupPromise: Promise<Lookup | null> | null = null;

/**
 * Builds `component name → its files` for each bucket folder.
 *
 * Every directory is a candidate, keyed by its normalised name, because a
 * component is not always a folder with an `index.tsx` in it —
 * `screens/empty-state/` holds only a `v1/` subfolder. Ranking settles the
 * collisions: a directory holding a plausible entry point beats one that does
 * not, and among equals the shallower path wins — the same tie-break the flat
 * sync used.
 */
function buildLookup(index: CodebaseIndex): Lookup {
  const lookup: Lookup = new Map();

  for (const [folder, { files }] of Object.entries(index.folders)) {
    // dir -> whether it directly holds an entry point.
    const directories = new Map<string, boolean>();

    for (const entry of files) {
      const segments = entry.path.split("/");
      const fileName = segments.pop()!;

      // Register the file's own directory and every ancestor of it.
      for (let depth = segments.length; depth > 0; depth -= 1) {
        const dir = segments.slice(0, depth).join("/");
        const isRoot =
          depth === segments.length &&
          mainCandidates(normalizeDirName(segments[depth - 1]!)).includes(fileName);

        directories.set(dir, (directories.get(dir) ?? false) || isRoot);
      }
    }

    const chosen = new Map<string, { dir: string; hasEntry: boolean }>();

    for (const [dir, hasEntry] of directories) {
      const name = normalizeDirName(dir.split("/").pop()!);
      const current = chosen.get(name);

      if (current) {
        if (current.hasEntry && !hasEntry) continue;
        if (current.hasEntry === hasEntry) {
          if (current.dir.split("/").length <= dir.split("/").length) continue;
        }
      }

      chosen.set(name, { dir, hasEntry });
    }

    const byComponent = new Map<string, ComponentFiles>();
    for (const [name, { dir }] of chosen) {
      byComponent.set(name, { dir, files: new Map() });
    }

    // Attach every file that lives under a component root, nested ones included.
    for (const entry of files) {
      for (const bucket of byComponent.values()) {
        if (!entry.path.startsWith(`${bucket.dir}/`)) continue;
        bucket.files.set(entry.path.slice(bucket.dir.length + 1), entry);
      }
    }

    lookup.set(folder, byComponent);
  }

  return lookup;
}

async function getLookup() {
  lookupPromise ??= (async () => {
    const index = await loadIndex();
    if (!index) {
      lookupPromise = null;
      return null;
    }
    return buildLookup(index);
  })();

  return lookupPromise;
}

/**
 * The object key for one file of a component, or null when it is not there.
 *
 * `fileName` is the canonical name the docs use — `index.tsx` and `types.ts`
 * expand to the candidate lists above, anything else is matched literally.
 */
export async function resolveCodebaseKey(
  folder: keyof typeof CODEBASE_FOLDERS,
  component: string,
  fileName: string,
): Promise<string | null> {
  const lookup = await getLookup();
  const found = lookup?.get(folder)?.get(normalizeDirName(component));
  if (!found) return null;

  for (const candidate of candidatesFor(fileName, component)) {
    const entry = found.files.get(candidate);
    if (entry) return entry.key;
  }

  return null;
}

/* -------------------------------------------------------------------------- */
/* reading                                                                     */
/* -------------------------------------------------------------------------- */

const fileCache = new Map<string, Promise<string | null>>();

/** Fetches one object. Cached per key for the lifetime of the build. */
export function fetchCodebaseFile(key: string): Promise<string | null> {
  const cached = fileCache.get(key);
  if (cached) return cached;

  const pending = (async () => {
    try {
      // Same reasoning as the index: a component's source changes, and a
      // build that reuses last week's copy is worse than one that refetches.
      // `fileCache` keeps it to one request per key per build.
      const response = await fetchWithRetry(key);
      if (response.status === 404) return null;
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return await response.text();
    } catch (error) {
      const message = `[codebase] could not read ${key}: ${(error as Error).message}`;

      // The index listed this object, so failing to read it is a fault in the
      // request, not an answer about the bucket — and the memoisation below
      // would otherwise make one blip permanent for the rest of the build.
      // Same reasoning as the index: better no deploy than a page that denies
      // source it can see in the listing.
      if (process.env.NODE_ENV === "production") throw new Error(message);

      console.warn(message);
      // The miss stays memoised. Every page that reads this key has to agree on
      // what it holds — a key that reads null for one page and its source for
      // the next is what leaves the segment output inconsistent.
      return null;
    }
  })();

  fileCache.set(key, pending);
  return pending;
}

/**
 * The component's own directory inside the bucket folder, e.g. `base/button`.
 * Null when the component is not in the bucket.
 */
export async function resolveComponentDir(
  folder: keyof typeof CODEBASE_FOLDERS,
  component: string,
): Promise<string | null> {
  const lookup = await getLookup();
  return lookup?.get(folder)?.get(normalizeDirName(component))?.dir ?? null;
}

export interface ComponentFileRef {
  /** Path relative to the component's own folder, e.g. `internal/test.ts`. */
  path: string;
  /** Full object key in the bucket. */
  key: string;
  size: number;
}

/**
 * Every file in a component's folder, in the order a file tree should show it.
 *
 * The docs used to hand-list `index.tsx` and `types.ts`, which hid everything
 * else a component actually ships — `conf.ts`, `const.ts`, `utils.ts`, nested
 * `hooks/` and `types/` directories. The bucket mirrors the folder as it is, so
 * the tree can simply show it.
 */
export async function listComponentFiles(
  folder: keyof typeof CODEBASE_FOLDERS,
  component: string,
): Promise<ComponentFileRef[]> {
  const lookup = await getLookup();
  const found = lookup?.get(folder)?.get(normalizeDirName(component));
  if (!found) return [];

  const entryPoints = new Set(mainCandidates(component));

  return [...found.files.entries()]
    // A component folder can carry an image or a font next to its code; those
    // belong in the folder but not in a syntax-highlighted source tree.
    .filter(([path]) => CODE_FILE.test(path))
    .map(([path, entry]) => ({ path, key: entry.key, size: entry.size }))
    .sort((a, b) => {
      const depthA = a.path.includes("/");
      const depthB = b.path.includes("/");

      // Loose files before directories, so the entry point is never buried.
      if (depthA !== depthB) return depthA ? 1 : -1;

      // The component's own entry point leads.
      const entryA = entryPoints.has(a.path);
      const entryB = entryPoints.has(b.path);
      if (entryA !== entryB) return entryA ? -1 : 1;

      return a.path.localeCompare(b.path);
    });
}

/**
 * Every file under one directory of a bucket folder, in the same order
 * `listComponentFiles` returns a component's own.
 *
 * The lookup above resolves a component by name, which is what the component
 * docs have: a slug. The blocks catalogue has the path instead — each mockup
 * records the block it is a screenshot of — and a name lookup is the wrong tool
 * for it twice over. `air-bnb-v2` is not the `airbnb-v2` its screenshot is
 * called, and a block directory sits three levels deep, so a collision with a
 * shallower directory of the same name would silently win. An explicit path
 * has neither problem.
 */
export async function listFilesInDir(
  folder: keyof typeof CODEBASE_FOLDERS,
  dir: string,
): Promise<ComponentFileRef[]> {
  const index = await loadIndex();
  const files = index?.folders[folder]?.files;
  if (!files) return [];

  const prefix = `${dir.replace(/\/+$/, "")}/`;

  return files
    .filter((entry) => entry.path.startsWith(prefix))
    .map((entry) => ({
      path: entry.path.slice(prefix.length),
      key: entry.key,
      size: entry.size,
    }))
    // Nothing but code, and never a nested file above a loose one.
    .filter((ref) => CODE_FILE.test(ref.path))
    .sort((a, b) => {
      const nestedA = a.path.includes("/");
      const nestedB = b.path.includes("/");
      if (nestedA !== nestedB) return nestedA ? 1 : -1;

      // The entry point leads, whatever the folder is called.
      const entryA = a.path === "index.tsx" || a.path === "index.ts";
      const entryB = b.path === "index.tsx" || b.path === "index.ts";
      if (entryA !== entryB) return entryA ? -1 : 1;

      return a.path.localeCompare(b.path);
    });
}

/**
 * One file of a component, read from the bucket.
 *
 * Null when the component is not in the index or the object is not there —
 * a sync gap, which the caller shows as a note instead of a broken page.
 */
export async function readComponentFile(
  folder: keyof typeof CODEBASE_FOLDERS,
  component: string,
  fileName: string,
): Promise<string | null> {
  const key = await resolveCodebaseKey(folder, component, fileName);
  return key ? await fetchCodebaseFile(key) : null;
}
